#!/usr/bin/env node
/**
 * sync-vault.js
 *
 * LOCAL:  reads .md files from your iCloud vault path on disk.
 * CI:     clones the vault GitHub repo (shallow, blogs folder only).
 *
 * Run:  npm run sync-blogs
 */

const fs            = require('fs');
const path          = require('path');
const os            = require('os');
const { execSync }  = require('child_process');

let matter;
try {
  matter = require('gray-matter');
} catch {
  console.error('gray-matter not found. Run: npm install gray-matter');
  process.exit(1);
}

const { vaultRepoUrl, localVaultPath, blogFolder } = require('../vault.config.js');

// ── Resolve the blogs directory ───────────────────────────────────────────────
const isCI = process.env.CI === 'true' || process.env.CF_PAGES === '1';
let blogsDir;
let tempDir = null;

if (isCI) {
  // Clone vault repo from GitHub (shallow — only the blogs folder)
  tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'vault-'));

  // Support private repos via VAULT_REPO_TOKEN env var
  const token   = process.env.VAULT_REPO_TOKEN;
  const cloneUrl = token
    ? vaultRepoUrl.replace('https://', `https://${token}@`)
    : vaultRepoUrl;

  console.log(`Cloning vault from ${vaultRepoUrl} ...`);
  try {
    execSync(
      `git clone --depth=1 --filter=blob:none --sparse "${cloneUrl}" "${tempDir}"`,
      { stdio: 'pipe' }
    );
    execSync(
      `git -C "${tempDir}" sparse-checkout set "${blogFolder}"`,
      { stdio: 'pipe' }
    );
  } catch (err) {
    console.error('Failed to clone vault repo:', err.message);
    console.error('Check vaultRepoUrl in vault.config.js and VAULT_REPO_TOKEN if private.');
    process.exit(1);
  }

  blogsDir = path.join(tempDir, blogFolder);
} else {
  // Local dev — read from iCloud-synced vault
  blogsDir = path.join(localVaultPath, blogFolder);
}

// ── Check blogs folder exists ─────────────────────────────────────────────────
if (!fs.existsSync(blogsDir)) {
  const hint = isCI
    ? `Vault cloned but '${blogFolder}/' folder not found inside it.\nCheck blogFolder in vault.config.js.`
    : `Local vault blogs folder not found: ${blogsDir}\nCheck localVaultPath in vault.config.js.`;
  console.warn('Warning:', hint);
  console.warn('Writing empty blog list.');
  writeOutput([]);
  process.exit(0);
}

// ── Read .md files ────────────────────────────────────────────────────────────
const files = fs
  .readdirSync(blogsDir)
  .filter((f) => f.endsWith('.md'))
  .sort();

if (files.length === 0) {
  console.warn(`No .md files found in ${blogsDir}. Writing empty blog list.`);
  writeOutput([]);
  process.exit(0);
}

const posts = [];

files.forEach((filename, idx) => {
  const filePath = path.join(blogsDir, filename);
  const raw      = fs.readFileSync(filePath, 'utf8');
  const parsed   = matter(raw);
  const fm       = parsed.data;

  if (fm.draft === true) return;

  const title    = fm.title || filename.replace(/\.md$/, '').replace(/-/g, ' ');
  const rawDate  = fm.date ? new Date(fm.date) : new Date(fs.statSync(filePath).mtime);
  const date     = rawDate.toISOString().split('T')[0];
  const tags     = Array.isArray(fm.tags)
    ? fm.tags.map(String)
    : typeof fm.tags === 'string'
    ? fm.tags.split(',').map((t) => t.trim()).filter(Boolean)
    : [];

  let summary = fm.summary || '';
  if (!summary) {
    const firstPara = parsed.content
      .split('\n')
      .map((l) => l.trim())
      .find((l) => l.length > 0 && !l.startsWith('#') && !l.startsWith('!'));
    summary = firstPara ? firstPara.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') : '';
    if (summary.length > 200) summary = summary.slice(0, 197) + '…';
  }

  const slug = filename.replace(/\.md$/, '').toLowerCase().replace(/\s+/g, '-');

  let content = parsed.content
    .replace(/!\[\[([^\]]+)\]\]/g, '')
    .replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, '$2')
    .replace(/\[\[([^\]]+)\]\]/g, '$1')
    .replace(/\s*\^[a-zA-Z0-9-]+$/gm, '');

  posts.push({ id: idx + 1, slug, title, date, summary, tags, coverImage: fm.coverImage || '', content });
});

posts.sort((a, b) => new Date(b.date) - new Date(a.date));
posts.forEach((p, i) => { p.id = i + 1; });

writeOutput(posts);
console.log(`✓ Synced ${posts.length} post(s) → src/data/blogs.js`);

// ── Write output ──────────────────────────────────────────────────────────────
function writeOutput(data) {
  const outPath = path.resolve(__dirname, '../src/data/blogs.js');
  const content = [
    '// AUTO-GENERATED by scripts/sync-vault.js — do not edit by hand.',
    '// Run:  npm run sync-blogs',
    '',
    'const blogs = ' + JSON.stringify(data, null, 2) + ';',
    '',
    'export default blogs;',
    '',
  ].join('\n');
  fs.writeFileSync(outPath, content, 'utf8');
}
