#!/usr/bin/env node
/**
 * sync-vault.js
 *
 * Reads every .md file from your Obsidian vault's blog folder,
 * parses frontmatter + body, and writes src/data/blogs.js.
 *
 * Run:  npm run sync-blogs
 */

const fs   = require('fs');
const path = require('path');

let matter;
try {
  matter = require('gray-matter');
} catch {
  console.error('gray-matter not found. Run: npm install gray-matter');
  process.exit(1);
}

// ── Load config ──────────────────────────────────────────────────────────────
const configPath = path.resolve(__dirname, '../vault.config.js');
if (!fs.existsSync(configPath)) {
  console.error('vault.config.js not found at project root.');
  process.exit(1);
}
const { vaultPath, blogFolder } = require(configPath);

const blogsDir = path.join(vaultPath, blogFolder);

if (!fs.existsSync(blogsDir)) {
  console.error(`Blog folder not found: ${blogsDir}`);
  console.error('Check vault.config.js — make sure vaultPath and blogFolder are correct.');
  process.exit(1);
}

// ── Read .md files ────────────────────────────────────────────────────────────
const files = fs
  .readdirSync(blogsDir)
  .filter((f) => f.endsWith('.md'))
  .sort();

if (files.length === 0) {
  console.warn(`No .md files found in ${blogsDir}. Writing empty blog list.`);
}

const posts = [];

files.forEach((filename, idx) => {
  const filePath = path.join(blogsDir, filename);
  const raw      = fs.readFileSync(filePath, 'utf8');
  const parsed   = matter(raw);
  const fm       = parsed.data;

  // Skip drafts
  if (fm.draft === true) return;

  // Title: frontmatter title or filename without extension
  const title = fm.title || filename.replace(/\.md$/, '').replace(/-/g, ' ');

  // Date: frontmatter date or file mtime
  const rawDate  = fm.date ? new Date(fm.date) : new Date(fs.statSync(filePath).mtime);
  const date     = rawDate.toISOString().split('T')[0];

  // Tags
  const tags = Array.isArray(fm.tags)
    ? fm.tags.map(String)
    : typeof fm.tags === 'string'
    ? fm.tags.split(',').map((t) => t.trim()).filter(Boolean)
    : [];

  // Summary: frontmatter summary or first non-heading, non-empty paragraph
  let summary = fm.summary || '';
  if (!summary) {
    const firstPara = parsed.content
      .split('\n')
      .map((l) => l.trim())
      .find((l) => l.length > 0 && !l.startsWith('#') && !l.startsWith('!'));
    summary = firstPara ? firstPara.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') : '';
    if (summary.length > 200) summary = summary.slice(0, 197) + '…';
  }

  // Slug from filename
  const slug = filename.replace(/\.md$/, '').toLowerCase().replace(/\s+/g, '-');

  // Strip Obsidian-specific syntax from content before embedding:
  //  - [[wikilinks]]  → just the label
  //  - ![[embeds]]    → removed
  //  - ^block-refs    → removed
  let content = parsed.content
    .replace(/!\[\[([^\]]+)\]\]/g, '')           // remove embed links
    .replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, '$2') // [[Page|Label]] → Label
    .replace(/\[\[([^\]]+)\]\]/g, '$1')          // [[Page]] → Page
    .replace(/\s*\^[a-zA-Z0-9-]+$/gm, '');       // remove block IDs

  posts.push({ id: idx + 1, slug, title, date, summary, tags, coverImage: fm.coverImage || '', content });
});

// Sort newest first
posts.sort((a, b) => new Date(b.date) - new Date(a.date));
// Re-assign sequential ids after sort
posts.forEach((p, i) => { p.id = i + 1; });

// ── Generate blogs.js ─────────────────────────────────────────────────────────
const outPath = path.resolve(__dirname, '../src/data/blogs.js');

const lines = [
  '// AUTO-GENERATED by scripts/sync-vault.js — do not edit by hand.',
  '// Run:  npm run sync-blogs',
  '',
  'const blogs = ' + JSON.stringify(posts, null, 2) + ';',
  '',
  'export default blogs;',
  '',
];

fs.writeFileSync(outPath, lines.join('\n'), 'utf8');

console.log(`✓ Synced ${posts.length} post(s) from ${blogsDir}`);
console.log(`  → ${outPath}`);
